const MISAResource = {
    TextVi: {
        Header: {
          CompanyName: "Công ty TNHH SONG VIỆT - Misatest",
          EmployeeName: "Phạm Đình Duy",
        },
        Content: {
          Title: "Nhân viên",
          Add: "Thêm mới nhân viên",
        },
        EmployeeList: {
          Search: "Tìm kiếm theo mã, tên nhân viên",
          /* Tên cột */
          EmployeeCode: "Mã nhân viên",
          EmployeeName: "Tên nhân viên",
          Gender: "Giới tính",
          DateOfBirth: "Ngày sinh",
          Identity: "Số CMND",
          PositionName: "Chức danh",
           DepartmentName: "Tên đơn vị",
          BankNumber: "Số tài khoản",
          BankName: "Tên ngân hàng",
          BankBranch: "Chi nhánh",
          Function: "Chức năng",
          /* Tên chức năng */
          Edit: "Sửa",
          Replicate: "Nhân bản",
          Delete: "Xoá",
          Stop: "Ngừng sử dụng",
          RecordInPage: " bản ghi trên 1 trang",
        },
        EmployeeDetail: {
          DetailTitle: "Thông tin nhân viên",
          EmployeeCode: "Mã",
          EmployeeName: "Tên",
          DateOfBirth: "Ngày sinh",
          Gender: "Giới tính",
          DepartmentName: "Đơn vị",
          IdentityNumber: "Số CMND",
          IdentityDate: "Ngày cấp",
          PositionName: "Chức danh",
          IdentityPlace: "Nơi cấp",
          Address: "Địa chỉ",
          Phone: "ĐT di động",
          Landline: "ĐT cố định",
          Email: "Email",
          BankAccountNumber: "TK ngân hàng",
          BankName: "Tên ngân hàng",
          BankBranch: "Chi nhánh",
    
          /* Tên chức năng */
          Cancel: "Huỷ",
          Close: "Đóng",
          Save: "Cất",
          SaveAndAdd: "Cất và Thêm",
          Insert: "Thêm",
          Update: "Sửa",
          Accept: "Đồng ý",
          Yes: "Có",
          No: "Không",
        },
        Dialog: {
          Save: "Cất",
          NotSave: "Không cất",
          No: "Không",
          Yes: "Có",
          Close: "Đóng",
          Cancel: "Huỷ",
          Delete: "Xoá",
          Accept: "Đồng ý",
          Title: {
            Delete: "Xoá nhân viên",
            DeleteMany : "Bạn có thực sự muốn xóa những nhân viên đã chọn không?",
            Warning: "Cảnh báo",
            Change: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không? ",
            Error: "Có lỗi!",
          },
          Text: {
            Save: "Bạn có muốn cất không?",
            Employee: "Nhân viên",
            After: "sẽ bị xoá.",
          },
        },
        ErrorMessage: {
          DuplicateCode: "Mã nhân viên đã tồn tại.",
          EmptyCode: "Mã không được để trống.",
          EmptyName: "Tên nhân viên không được để trống.",
          EmptyDepartmentName: "Tên đơn vị không được để trống.",
        },
        //
        ToastMessage: {
          Success: {
            Title: "Thành công!",
            Delete: "Nhân viên đã bị xoá.",
            Insert: "Nhân viên đã được thêm.",
            Update: "Nhân viên đã được thay đổi.",
          },
        },
        ToolTip: {
          Help: "Giúp (F1)",
          Close: "Đóng (ESC)",
          IdentityNumber: "Số chứng minh nhân dân",
          Phone: "Số điện thoại di động",
          Landline: "Số điện thoại cố định",
          BankAccountNumber:"Số tài khoản ngân hàng",
          Save: "Cất (Ctrl+S)",
          SaveAndAdd: "Cất và Thêm (Ctrl+Shift+S)",
        }
    },
}
export default MISAResource;